on:
  push:
  pull_request:

name: Website

jobs:
  build:
    name: Build Examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.5.0

      - name: Build Website
        run: |
          cd website
          trunk build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.9
        with:
          path: website/dist

  deploy:
    name: Deploy Pages
    needs:
      - build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v2.0.2
